
SET(OFLANDR_INSTALL_LIB_PATH "lib")
SET(OFLANDR_INSTALL_INCLUDE_PATH "include/openfluid/landr")

SET(OFLANDR_DIST_PATH "dist")
SET(OFLANDR_DIST_LIB_PATH "${OFLANDR_DIST_PATH}/${OFLANDR_INSTALL_LIB_PATH}")

SET(OFLANDR_TESTS_INPUT_PATH "${CMAKE_SOURCE_DIR}/resources/tests")
SET(OFLANDR_TESTS_OUTPUT_PATH "${CMAKE_BINARY_DIR}/tests/output")
SET(OFLANDR_TESTS_BINARY_PATH "${CMAKE_BINARY_DIR}/tests/bin")